haidaraM/ansible-playbook-grapher

ansibleplaybookgrapher/cli.py, requirements.txt, tests/test_cli.py, tests/test_grapher.py
fix #18
This change is needed because of https://github.com/ansible/ansible/pull/50069. The new CLI in this PR should be used in the future when we drop support for Ansible < 2.8.
=> fix #18: New CLI compatible with ansible 2.8

ansibleplaybookgrapher/utils.py
This simple fix makes sure that an element exists, before (trying to) assign it. It fixes #20
=> Fix for #20: Make sure that an element exists before assigning it

requirements.txt
lxml has a security release in version 4.6.3, however I cannot upgrade to it due to ansible-playbook-grapher pinning it directly. As an installable tool that can interact with a virtualenv, ansible-playbook-grapher should not pin dependencies but declare ranges up until the next backwards-incompatible version, to allow users to fetch such upgrades.
=> Unpin requirements

.github/workflows/testing.yaml, Makefile, README.md, ansibleplaybookgrapher/cli.py, requirements.txt, tests/test_cli.py, tests/test_grapher.py
Drop support for ansible 2.8. The grapher requires at least ansible 2.9
=> fix: Drop support for ansible 2.8

CHANGELOG.md, ansibleplaybookgrapher/data/highlight-hover.js, ansibleplaybookgrapher/graph.py, ansibleplaybookgrapher/parser.py, ansibleplaybookgrapher/renderer.py, ansibleplaybookgrapher/utils.py, tests/fixtures/with_block.yml, tests/test_playbook_grapher.py
=> feat: Add ability do distinguish the explicit block on the graph

.github/workflows/testing.yaml, CHANGELOG.md, Makefile, README.md, ansibleplaybookgrapher/cli.py, ansibleplaybookgrapher/parser.py, ansibleplaybookgrapher/utils.py, requirements.txt, test_install.sh
Since the [Ansible package have been split](https://www.ansible.com/blog/ansible-3.0.0-qa), this PR removes the old version and keep only `ansible-core` since it's the only package the grapher needs. 
As such, the minimum required version is now **ansible-core >= 2.11** and **python 3.8**
=> fix: Drop support for ansible 2.9, 2.10 and add ansible 2.11.6

ansibleplaybookgrapher/renderer.py, tests/test_playbook_grapher.py
=> fix: Properly rank the edges in the graphs and sub-graphs

ansibleplaybookgrapher/data/highlight-hover.js, ansibleplaybookgrapher/graph.py, ansibleplaybookgrapher/parser.py, ansibleplaybookgrapher/postprocessor.py, ansibleplaybookgrapher/renderer.py, tests/test_graph.py, tests/test_parser.py, tests/test_playbook_grapher.py
The EdgeNode is not really needed. The information it contains is owned by the destination node.
This is an internal change that should not impact the rendered graph.
=> refactor(internal): Remove useless EdgeNode

requirements.txt
Fixes #113 by further constraining the ansible-core version. On the long run ansible-playbook-grapher should probably be made compatible with that version.
=> Forbid incompatible ansible-core versions >= 2.13

ansibleplaybookgrapher/__init__.py, ansibleplaybookgrapher/data/highlight-hover.js, ansibleplaybookgrapher/graph.py, ansibleplaybookgrapher/parser.py, ansibleplaybookgrapher/postprocessor.py, ansibleplaybookgrapher/renderer.py, ansibleplaybookgrapher/utils.py, tests/fixtures/include_role.yml, tests/fixtures/multi-plays.yml, tests/fixtures/roles/nested_include_role/tasks/main.yml, tests/test_parser.py, tests/test_playbook_grapher.py
Related to #110 and some improvements:
- The role node style has been changed to filled. 
- When a role is used multiple times, its color is a combination of all the plays that use it. All the external edges are also a combination of these colors
=> fix: Render a single node when multiple playbooks use the same role

ansibleplaybookgrapher/postprocessor.py, ansibleplaybookgrapher/utils.py, requirements.txt
=> fix: Improve the position of the conditions on the edges

ansibleplaybookgrapher/graph.py, ansibleplaybookgrapher/graphbuilder.py, ansibleplaybookgrapher/parser.py, ansibleplaybookgrapher/postprocessor.py, ansibleplaybookgrapher/utils.py, tests/fixtures/include_role.yml, tests/fixtures/roles/nested_include_role/tasks/main.yml, tests/test_graph.py, tests/test_parser.py, tests/test_playbook_grapher.py
=> fix: Roles usages and do not use multiple edges for role tasks

ansibleplaybookgrapher/data/highlight-hover.js
=> fix: Avoid recursive endless loop when a role references itself

.github/workflows/lint.yml, .github/workflows/testing.yaml, Makefile, README.md, ansibleplaybookgrapher/__init__.py, ansibleplaybookgrapher/cli.py, ansibleplaybookgrapher/graph_model.py, ansibleplaybookgrapher/grapher.py, ansibleplaybookgrapher/parser.py, ansibleplaybookgrapher/renderer/__init__.py, ansibleplaybookgrapher/renderer/graphviz/__init__.py, ansibleplaybookgrapher/renderer/graphviz/postprocessor.py, ansibleplaybookgrapher/renderer/json.py, ansibleplaybookgrapher/renderer/mermaid.py, ansibleplaybookgrapher/utils.py, ruff.toml, setup.py, tests/__init__.py, tests/conftest.py, tests/generate-job-summary.py, tests/requirements_tests.txt, tests/test_cli.py, tests/test_graph_model.py, tests/test_graphviz_postprocessor.py, tests/test_graphviz_renderer.py, tests/test_json_renderer.py, tests/test_mermaid_renderer.py, tests/test_parser.py, tests/test_utils.py
- Code cleanup with ruff
- Fix typos
=> ci: Use ruff for linting and format

README.md, ansibleplaybookgrapher/cli.py, ansibleplaybookgrapher/graph_model.py, ansibleplaybookgrapher/parser.py, ansibleplaybookgrapher/renderer/__init__.py, ansibleplaybookgrapher/renderer/graphviz/__init__.py, ansibleplaybookgrapher/renderer/json.py, ansibleplaybookgrapher/renderer/mermaid.py, ansibleplaybookgrapher/utils.py, ruff.toml, tests/fixtures/handlers-in-role.yml, tests/fixtures/handlers.yml, tests/fixtures/json-schemas/v1.json, tests/fixtures/roles/role-with-handlers/handlers/main.yml, tests/fixtures/roles/role-with-handlers/tasks/main.yml, tests/test_cli.py, tests/test_graph_model.py, tests/test_graphviz_renderer.py, tests/test_json_renderer.py, tests/test_mermaid_renderer.py, tests/test_parser.py
Related #214 
- Add the handlers to the graph with `--show-handlers`. **This is the initial support for handlers.** They are by default added at the end of the play and roles only. This doesn't reflect Ansible behavior. 
- Changes the shape of the graphviz node to make it consistent with Mermaid. The tasks will be rectangle instead of `octagon`: https://graphviz.org/doc/info/shapes.html
- Refactor how the node/task index are computed given we can now add handlers after all the tasks are parsed.
- Add a new `display_name()` method to the node for a friendly name for the graph. This removes the of passing the `node_label_prefix` in multiple places.
- Remove the class **CompositeTasksNode** as it is no longer needed anymore. 
- Remove the play name from the edge going from playbook to the …
=> feat: Add initial support for handlers

CHANGELOG.md, README.md, ansibleplaybookgrapher/cli.py, ansibleplaybookgrapher/graph_model.py, ansibleplaybookgrapher/grapher.py, ansibleplaybookgrapher/parser.py, ansibleplaybookgrapher/renderer/__init__.py, ansibleplaybookgrapher/renderer/graphviz/__init__.py, ansibleplaybookgrapher/renderer/json.py, ansibleplaybookgrapher/renderer/mermaid.py, ansibleplaybookgrapher/utils.py, tests/fixtures/nested-include-role.yml, tests/fixtures/roles/role-with-tagged-tasks/tasks/main.yml, tests/fixtures/tags-and-roles.yml, tests/test_graph_model.py, tests/test_graphviz_renderer.py, tests/test_json_renderer.py, tests/test_parser.py
Related to #226
- fix: The tags on the role itself should not be evaluated. Instead, what we care about is the tasks (they inherit the tags set on the roles). More info [here.](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html#adding-tags-to-roles) 
- "Empty roles" are no longer displayed by default. An empty role is a role with no tasks (after applying the tags filters for example). This is the same behavior as the option `--hide-empty-plays` but with roles. **I will eventually drop `--hide-empty-plays` to make this the default behavior in the future.**
- docs: Add a comparison matrix for the different renderers
- (Internal) Moved some flags out of the parser to the renderer instead. The whole playbook and all the tasks and roles (except the excluded ones) are …
=> fix: Properly handle tags on roles (refactor)

CHANGELOG.md, README.md, ansibleplaybookgrapher/cli.py, tests/test_graphviz_renderer.py
Ansible executor engine treats them very differently:
- All `import*` statements are pre-processed at the time playbooks are parsed.
- All `include*` statements are processed as they are encountered during the execution of the playbook.
From https://docs.ansible.com/ansible/2.9/user_guide/playbooks_reuse_includes.html
---
What does mean for you: The tasks imported by an `import_role` are now **always added** to the graph regardless of the usage of `--include-role-tasks`. This behavior was introduced by #228. Since the `import*` statements are pre-processed when the playbook is parsed, it's not trivial to know the tasks are from an `import_role`. I might eventually change this if people want the same output as the `include_role` (a dedicated note for the import role as well).
From this …
=> doc/tests: import_role doesn't have the same behavior as include_role

CHANGELOG.md, README.md, ansibleplaybookgrapher/cli.py, ansibleplaybookgrapher/graph_model.py, ansibleplaybookgrapher/renderer/__init__.py, tests/fixtures/json-schemas/v1.json, tests/fixtures/with_block.yml, tests/test_graph_model.py, tests/test_json_renderer.py
- Empty blocks are no longer added to the graph.
- Tasks in role should not have the `[task]` as a prefix.
- `Node.index` can be `None`. This mean they will not be added to the graph (for graphviz and mermaid).
- Fix `CompositeNode.is_empty()`
=> fix: Remove empty blocks, fix index + rename some methods

ansibleplaybookgrapher/parser.py
=> fix: Do not fail when a Task is missing the listen attribute

CHANGELOG.md, README.md, ansibleplaybookgrapher/cli.py, ansibleplaybookgrapher/data/graph.css, ansibleplaybookgrapher/data/highlight-hover.js, ansibleplaybookgrapher/renderer/graphviz/__init__.py, ansibleplaybookgrapher/renderer/graphviz/postprocessor.py, tests/test_graph_model.py, tests/test_graphviz_renderer.py
This PR implements collapsible nodes in the SVG output for the Ansible Playbook Grapher, addressing [issue #77](https://github.com/haidaraM/ansible-playbook-grapher/issues/77).
- Adds a collapse/expand button to all role, play, and block nodes in the SVG output.
- Clicking the button hides or shows all descendant nodes and edges recursively, making large graphs easier to navigate.
- The button is always visible for the current node, so users can always expand collapsed nodes.
- The implementation uses the existing `<link>` structure in the SVG to determine which nodes and edges to hide/show, with no extra attributes required.
- The code is generalized for all node types (role, play, block).
- Added a new CLI flag `--collapsible-nodes` to make this feature optional (disabled by default).
- …
=> feat(svg): Add collapsible nodes for roles, plays, and blocks in SVG output
